name: smart_controller
version: 0.1.5+6

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.3.4

flutter:
  uses-material-design: true
